#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npx --no-install commitlint --edit "$1"
npx --no-install commitlint --edit "$1" ||
{ 
    echo "不符合约定式提交Conventional Commits规范,请使用正确格式
         \n如: feat: description
         \n详情请查看https://www.conventionalcommits.org/zh-hans/v1.0.0/";
    exec < /dev/tty && npx --no-install cz --hook || exit 1;  
}
